// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE

import * as Utils from "./utils.bs.js";

function create_marble(factory, x, y, w, h) {
  var marble = factory.sprite(x, y, "marble");
  marble.displayWidth = w;
  marble.displayHeight = h;
  return marble;
}

function draw_card(scene, pattern, x, y, w, h) {
  console.log("pattern", pattern);
  var object_factor = scene.add;
  var card_container = object_factor.container();
  var grid_w_f = 3;
  var grid_h_f = 3;
  var s_width = w / grid_w_f;
  var s_height = h / grid_h_f;
  var match = Utils.scale_marble_size(s_width, s_height, 30.0);
  var m_height = match[/* height */1];
  var m_width = match[/* width */0];
  for(var i = 0 ,i_finish = (grid_w_f | 0) - 1 | 0; i <= i_finish; ++i){
    for(var j = 0 ,j_finish = (grid_h_f | 0) - 1 | 0; j <= j_finish; ++j){
      var slot = object_factor.graphics();
      var s_x = j * s_width;
      var s_y = i * s_height;
      var param = parseInt("E1E2E1", 16);
      slot.lineStyle(5.0, param, 1.0);
      var param$1 = parseInt("bbdefb", 16);
      slot.fillStyle(param$1, 1.0);
      slot.beginPath();
      if (i === 0) {
        slot.moveTo(s_x, s_y);
        var param$2 = s_x + s_width;
        slot.lineTo(param$2, s_y);
      }
      var param$3 = s_x + s_width;
      slot.moveTo(param$3, s_y);
      var param$4 = s_y + s_height;
      var param$5 = s_x + s_width;
      slot.lineTo(param$5, param$4);
      var param$6 = s_y + s_height;
      slot.lineTo(s_x, param$6);
      if (j === 0) {
        slot.lineTo(s_x, s_y);
      }
      var param$7 = i * s_height;
      var param$8 = j * s_width;
      slot.fillRect(param$8, param$7, s_width, s_height);
      slot.strokePath();
      card_container.add(slot);
      console.log(i, j, pattern);
      if (Utils.get_unsafe(pattern, i, j) === 1.0) {
        var marble_sprite = create_marble(object_factor, s_x + s_width * 0.5, s_y + s_height * 0.5, m_width, m_height);
        card_container.add(marble_sprite);
      }
      
    }
  }
  card_container.setPosition(x, y);
  return /* () */0;
}

var grid_h = 3;

var grid_w = 3;

export {
  grid_h ,
  grid_w ,
  create_marble ,
  draw_card ,
  
}
/* Utils Not a pure module */
