// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE

import * as Block from "../../node_modules/bs-platform/lib/es6/block.js";
import * as Curry from "../../node_modules/bs-platform/lib/es6/curry.js";
import * as Belt_Array from "../../node_modules/bs-platform/lib/es6/belt_Array.js";
import * as Belt_MapString from "../../node_modules/bs-platform/lib/es6/belt_MapString.js";

function init(param) {
  return /* record */[
          /* last_move : record */[
            /* x */-1,
            /* y */-1,
            /* next_player */""
          ],
          /* players : [] */0,
          /* id */"",
          /* phase */"",
          /* hand : [] */0,
          /* winner */""
        ];
}

function mOVE(param_0) {
  return /* MOVE */Block.__(0, [param_0]);
}

function players(param_0) {
  return /* Players */Block.__(1, [param_0]);
}

function iD(param_0) {
  return /* ID */Block.__(2, [param_0]);
}

function hAND(param_0) {
  return /* HAND */Block.__(3, [param_0]);
}

function wINNER(param_0) {
  return /* WINNER */Block.__(4, [param_0]);
}

function initMap(param) {
  return Belt_MapString.empty;
}

function notify(listeners, key, state) {
  if (Belt_MapString.has(listeners, key)) {
    return Belt_Array.forEach(Belt_MapString.getExn(listeners, key), (function (fn) {
                  return Curry._1(fn, state);
                }));
  } else {
    return 0;
  }
}

function update_state(state, action) {
  switch (action.tag | 0) {
    case 0 : 
        return /* record */[
                /* last_move */action[0],
                /* players */state[/* players */1],
                /* id */state[/* id */2],
                /* phase */state[/* phase */3],
                /* hand */state[/* hand */4],
                /* winner */state[/* winner */5]
              ];
    case 1 : 
        return /* record */[
                /* last_move */state[/* last_move */0],
                /* players */action[0],
                /* id */state[/* id */2],
                /* phase */state[/* phase */3],
                /* hand */state[/* hand */4],
                /* winner */state[/* winner */5]
              ];
    case 2 : 
        return /* record */[
                /* last_move */state[/* last_move */0],
                /* players */state[/* players */1],
                /* id */action[0],
                /* phase */state[/* phase */3],
                /* hand */state[/* hand */4],
                /* winner */state[/* winner */5]
              ];
    case 3 : 
        return /* record */[
                /* last_move */state[/* last_move */0],
                /* players */state[/* players */1],
                /* id */state[/* id */2],
                /* phase */state[/* phase */3],
                /* hand */action[0],
                /* winner */state[/* winner */5]
              ];
    case 4 : 
        return /* record */[
                /* last_move */state[/* last_move */0],
                /* players */state[/* players */1],
                /* id */state[/* id */2],
                /* phase */state[/* phase */3],
                /* hand */state[/* hand */4],
                /* winner */action[0]
              ];
    
  }
}

function dispatch(state, listeners, key, action) {
  var new_state = update_state(state, action);
  notify(listeners, key, new_state);
  return new_state;
}

function subscribe(listeners, $$event, fn) {
  var new_list;
  try {
    var cur_listeners = Belt_MapString.getExn(listeners, $$event);
    new_list = Belt_Array.concat(cur_listeners, Belt_Array.make(1, fn));
  }
  catch (exn){
    new_list = Belt_Array.make(1, fn);
  }
  var newIndex = new_list.length;
  return /* tuple */[
          Belt_MapString.set(listeners, $$event, new_list),
          newIndex
        ];
}

function unsubscribe(listeners, $$event, idx) {
  try {
    return Belt_MapString.set(listeners, $$event, Belt_Array.keepWithIndex(Belt_MapString.getExn(listeners, $$event), (function (param, i) {
                      return i === idx;
                    })));
  }
  catch (exn){
    return listeners;
  }
}

var move_event = "move";

var players_event = "move";

var id_event = "id";

var hand_event = "hand";

var winner_event = "winner";

export {
  init ,
  move_event ,
  players_event ,
  id_event ,
  hand_event ,
  winner_event ,
  mOVE ,
  players ,
  iD ,
  hAND ,
  wINNER ,
  initMap ,
  notify ,
  update_state ,
  dispatch ,
  subscribe ,
  unsubscribe ,
  
}
/* No side effect */
